custom:
  #path: /Users/jin/Downloads
  path: /home/ubuntu/wwwroot
  key: 123456798
  salt: insona
  jwt:
    pri-key:
      path: jwt/pri.key
    pub-key:
      path: jwt/pub.key
    expiry: 120
  redis:
    prefix: InSona
  upload:
    file: ${custom.path}/static/uploads/file/
    dir: ${custom.path}/static/uploads/images/
    home: ${custom.path}/static/uploads/home/
    material: ${custom.path}/static/uploads/material/
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/insona?useUnicode\=true&characterEncoding\=utf-8&autoReconnect\=true
    username: 4AB769B3A315FEDE
    #prod
    password: D11A0751AE9ADEDC1ED3E31D009048EA
    #password: 03C811FEC3BB662218748E1D2FDAB5AD
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-init-sql: SELECT 1
      connection-test-query: SELECT 1
      maximum-pool-size: 200
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
  http:
    multipart:
      location: ${custom.path}/temp
      max-file-size: 20mb
      max-request-size: 20mb
    encoding:
      force-request: true
  resources:
    static-locations: classpath:/resources,classpath:/static/,file:${custom.path}/static
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null

logging:
  path: ${custom.path}/logs
  level:
    com.jieweifu: DEBUG

server:
  use-forward-headers: true
  port: 9527
  compression:
    enabled: true
    mime-types: application/json,text/html,text/xml,text/plain,text/css,application/javascript,image/gif,image/jpeg,image/png

httpClient:
  user:
    get_app_users: http://api.gizwits.com/app/users
    post_app_users: http://api.gizwits.com/app/users
    put_app_users: http://api.gizwits.com/app/users
    post_app_login: http://api.gizwits.com/app/login
    post_app_request_token: http://api.gizwits.com/app/request_token
    post_app_reset_password: http://api.gizwits.com/app/reset_password
    post_app_sms_code: http://api.gizwits.com/app/sms_code
    get_app_verify_codes: http://api.gizwits.com/app/verify/codes
    post_app_verify_codes: http://api.gizwits.com/app/verify/codes
    put_app_verify_codes: https://api.gizwits.com/app/verify/codes
  blind:
    post_app_bind_mac: http://api.gizwits.com/app/bind_mac
    delete_app_bindings: https://api.gizwits.com/app/bindings
    get_app_bindings: https://api.gizwits.com/app/bindings
    post_app_bind_latest: https://api.gizwits.com/app/bind_latest
    put_app_bindings_did: https://api.gizwits.com/app/bindings/{did}
    get_app_did_bindings: https://api.gizwits.com/app/{did}/bindings
    delete_app_did_bindings: https://api.gizwits.com/app/{did}/bindings
  share:
    get_app_sharing: https://api.gizwits.com/app/sharing
    post_app_sharing: https://api.gizwits.com/app/sharing?sharing_type={sharing_type}
    delete_app_sharing_id: https://api.gizwits.com/app/sharing/{id}
    put_app_sharing_id: https://api.gizwits.com/app/sharing/{id}
    get_app_sharing_code: https://api.gizwits.com/app/sharing/code/{code}
    post_app_sharing_code: https://api.gizwits.com/app/sharing/code/{code}
    put_app_sharing_idalias: https://api.gizwits.com/app/sharing/{id}/alias?user_alias={user_alias}
    post_app_sharing_did_transfer: https://api.gizwits.com/app/sharing/1/transfer?uid=1

snoti.boot.enable: true
snoti.boot.host: snoti.gizwits.com
snoti.boot.port: 2017
snoti.boot.maxFrameLength: 8192
