custom:
  path: D:/spring-files
  jwt:
    pri-key:
      path: jwt/pri.key
    pub-key:
      path: jwt/pub.key
    expiry: 120
  redis:
    prefix: InSona
  upload:
    dir: ${custom.path}/static/uploads/

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/insona?useUnicode\=true&characterEncoding\=utf-8&autoReconnect\=true
    username: 4AB769B3A315FEDE
    password: D11A0751AE9ADEDC1ED3E31D009048EA
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-init-sql: SELECT 1
      connection-test-query: SELECT 1
      maximum-pool-size: 200
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: 123456
  http:
    multipart:
      location: ${custom.path}/temp
      max-file-size: 20mb
      max-request-size: 20mb
    encoding:
      force-request: true
  resources:
    static-locations: classpath:/resources,classpath:/static/,file:${custom.path}/static
  profiles:
    active: dev

logging:
  path: ${custom.path}/logs
  level:
    com.jieweifu: DEBUG

server:
  use-forward-headers: true
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,text/html,text/xml,text/plain,text/css,application/javascript,image/gif,image/jpeg,image/png